import { MigrateDownArgs, MigrateUpArgs, sql } from "@payloadcms/db-postgres";

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    -- Step 1: Temporarily change the column type to remove dependency
    ALTER TABLE "public"."pages_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."blog_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."_blog_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."experience_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."_experience_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;

    -- Step 2: Drop the existing enum types
    DROP TYPE "public"."enum_pages_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum_blog_posts_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum__blog_posts_v_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum_experience_posts_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum__experience_posts_v_blocks_script_copy_btn_code_language";

    -- Step 3: Create new enum types
    CREATE TYPE "public"."enum_pages_blocks_script_copy_btn_code_language" AS ENUM('abap', 'actionscript-3', 'ada', 'angular-html', 'angular-ts', 'apache', 'apex', 'apl', 'applescript', 'ara', 'asciidoc', 'asm', 'astro', 'awk', 'ballerina', 'bat', 'beancount', 'berry', 'bibtex', 'bicep', 'blade', 'bsl', 'c', 'cadence', 'cairo', 'clarity', 'clojure', 'cmake', 'cobol', 'codeowners', 'codeql', 'coffee', 'common-lisp', 'coq', 'cpp', 'crystal', 'csharp', 'css', 'csv', 'cue', 'cypher', 'd', 'dart', 'dax', 'desktop', 'diff', 'docker', 'dotenv', 'dream-maker', 'edge', 'elixir', 'elm', 'emacs-lisp', 'erb', 'erlang', 'fennel', 'fish', 'fluent', 'fortran-fixed-form', 'fortran-free-form', 'fsharp', 'gdresource', 'gdscript', 'gdshader', 'genie', 'gherkin', 'git-commit', 'git-rebase', 'gleam', 'glimmer-js', 'glimmer-ts', 'glsl', 'gnuplot', 'go', 'graphql', 'groovy', 'hack', 'haml', 'handlebars', 'haskell', 'haxe', 'hcl', 'hjson', 'hlsl', 'html', 'html-derivative', 'http', 'hxml', 'hy', 'imba', 'ini', 'java', 'javascript', 'jinja', 'jison', 'json', 'json5', 'jsonc', 'jsonl', 'jsonnet', 'jssm', 'jsx', 'julia', 'kotlin', 'kusto', 'latex', 'lean', 'less', 'liquid', 'log', 'logo', 'lua', 'luau', 'make', 'markdown', 'marko', 'matlab', 'mdc', 'mdx', 'mermaid', 'mipsasm', 'mojo', 'move', 'narrat', 'nextflow', 'nginx', 'nim', 'nix', 'nushell', 'objective-c', 'objective-cpp', 'ocaml', 'pascal', 'perl', 'php', 'plsql', 'po', 'postcss', 'powerquery', 'powershell', 'prisma', 'prolog', 'proto', 'pug', 'puppet', 'purescript', 'python', 'qml', 'qmldir', 'qss', 'r', 'racket', 'raku', 'razor', 'reg', 'regexp', 'rel', 'riscv', 'rst', 'ruby', 'rust', 'sas', 'sass', 'scala', 'scheme', 'scss', 'sdbl', 'shaderlab', 'shellscript', 'shellsession', 'smalltalk', 'solidity', 'soy', 'sparql', 'splunk', 'sql', 'ssh-config', 'stata', 'stylus', 'svelte', 'swift', 'system-verilog', 'systemd', 'talonscript', 'tasl', 'tcl', 'templ', 'terraform', 'tex', 'toml', 'ts-tags', 'tsv', 'tsx', 'turtle', 'twig', 'typescript', 'typespec', 'typst', 'v', 'vala', 'vb', 'verilog', 'vhdl', 'viml', 'vue', 'vue-html', 'vyper', 'wasm', 'wenyan', 'wgsl', 'wikitext', 'wolfram', 'xml', 'xsl', 'yaml', 'zenscript', 'zig', 'adoc', 'batch', 'be', '1c', 'cdc', 'clj', 'ql', 'coffeescript', 'lisp', 'c++', 'c#', 'cs', 'cql', 'dockerfile', 'elisp', 'erl', 'ftl', 'f', 'for', 'f77', 'f90', 'f95', 'f03', 'f08', 'f18', 'f#', 'fs', 'gjs', 'gts', 'gql', 'hbs', 'hs', 'properties', 'js', 'fsl', 'jl', 'kt', 'kts', 'kql', 'lean4', 'makefile', 'md', 'mmd', 'mips', 'nar', 'nf', 'nu', 'objc', 'pot', 'potx', 'ps', 'ps1', 'protobuf', 'jade', 'py', 'perl6', 'regex', 'rb', 'rs', '1c-query', 'shader', 'bash', 'sh', 'shell', 'zsh', 'console', 'closure-templates', 'spl', 'styl', 'talon', 'tf', 'tfvars', 'lit', 'ts', 'tsp', 'typ'); -- Complete your list
    CREATE TYPE "public"."enum_blog_posts_blocks_script_copy_btn_code_language" AS ENUM('abap', 'actionscript-3', 'ada', 'angular-html', 'angular-ts', 'apache', 'apex', 'apl', 'applescript', 'ara', 'asciidoc', 'asm', 'astro', 'awk', 'ballerina', 'bat', 'beancount', 'berry', 'bibtex', 'bicep', 'blade', 'bsl', 'c', 'cadence', 'cairo', 'clarity', 'clojure', 'cmake', 'cobol', 'codeowners', 'codeql', 'coffee', 'common-lisp', 'coq', 'cpp', 'crystal', 'csharp', 'css', 'csv', 'cue', 'cypher', 'd', 'dart', 'dax', 'desktop', 'diff', 'docker', 'dotenv', 'dream-maker', 'edge', 'elixir', 'elm', 'emacs-lisp', 'erb', 'erlang', 'fennel', 'fish', 'fluent', 'fortran-fixed-form', 'fortran-free-form', 'fsharp', 'gdresource', 'gdscript', 'gdshader', 'genie', 'gherkin', 'git-commit', 'git-rebase', 'gleam', 'glimmer-js', 'glimmer-ts', 'glsl', 'gnuplot', 'go', 'graphql', 'groovy', 'hack', 'haml', 'handlebars', 'haskell', 'haxe', 'hcl', 'hjson', 'hlsl', 'html', 'html-derivative', 'http', 'hxml', 'hy', 'imba', 'ini', 'java', 'javascript', 'jinja', 'jison', 'json', 'json5', 'jsonc', 'jsonl', 'jsonnet', 'jssm', 'jsx', 'julia', 'kotlin', 'kusto', 'latex', 'lean', 'less', 'liquid', 'log', 'logo', 'lua', 'luau', 'make', 'markdown', 'marko', 'matlab', 'mdc', 'mdx', 'mermaid', 'mipsasm', 'mojo', 'move', 'narrat', 'nextflow', 'nginx', 'nim', 'nix', 'nushell', 'objective-c', 'objective-cpp', 'ocaml', 'pascal', 'perl', 'php', 'plsql', 'po', 'postcss', 'powerquery', 'powershell', 'prisma', 'prolog', 'proto', 'pug', 'puppet', 'purescript', 'python', 'qml', 'qmldir', 'qss', 'r', 'racket', 'raku', 'razor', 'reg', 'regexp', 'rel', 'riscv', 'rst', 'ruby', 'rust', 'sas', 'sass', 'scala', 'scheme', 'scss', 'sdbl', 'shaderlab', 'shellscript', 'shellsession', 'smalltalk', 'solidity', 'soy', 'sparql', 'splunk', 'sql', 'ssh-config', 'stata', 'stylus', 'svelte', 'swift', 'system-verilog', 'systemd', 'talonscript', 'tasl', 'tcl', 'templ', 'terraform', 'tex', 'toml', 'ts-tags', 'tsv', 'tsx', 'turtle', 'twig', 'typescript', 'typespec', 'typst', 'v', 'vala', 'vb', 'verilog', 'vhdl', 'viml', 'vue', 'vue-html', 'vyper', 'wasm', 'wenyan', 'wgsl', 'wikitext', 'wolfram', 'xml', 'xsl', 'yaml', 'zenscript', 'zig', 'adoc', 'batch', 'be', '1c', 'cdc', 'clj', 'ql', 'coffeescript', 'lisp', 'c++', 'c#', 'cs', 'cql', 'dockerfile', 'elisp', 'erl', 'ftl', 'f', 'for', 'f77', 'f90', 'f95', 'f03', 'f08', 'f18', 'f#', 'fs', 'gjs', 'gts', 'gql', 'hbs', 'hs', 'properties', 'js', 'fsl', 'jl', 'kt', 'kts', 'kql', 'lean4', 'makefile', 'md', 'mmd', 'mips', 'nar', 'nf', 'nu', 'objc', 'pot', 'potx', 'ps', 'ps1', 'protobuf', 'jade', 'py', 'perl6', 'regex', 'rb', 'rs', '1c-query', 'shader', 'bash', 'sh', 'shell', 'zsh', 'console', 'closure-templates', 'spl', 'styl', 'talon', 'tf', 'tfvars', 'lit', 'ts', 'tsp', 'typ');
    CREATE TYPE "public"."enum__blog_posts_v_blocks_script_copy_btn_code_language" AS ENUM('abap', 'actionscript-3', 'ada', 'angular-html', 'angular-ts', 'apache', 'apex', 'apl', 'applescript', 'ara', 'asciidoc', 'asm', 'astro', 'awk', 'ballerina', 'bat', 'beancount', 'berry', 'bibtex', 'bicep', 'blade', 'bsl', 'c', 'cadence', 'cairo', 'clarity', 'clojure', 'cmake', 'cobol', 'codeowners', 'codeql', 'coffee', 'common-lisp', 'coq', 'cpp', 'crystal', 'csharp', 'css', 'csv', 'cue', 'cypher', 'd', 'dart', 'dax', 'desktop', 'diff', 'docker', 'dotenv', 'dream-maker', 'edge', 'elixir', 'elm', 'emacs-lisp', 'erb', 'erlang', 'fennel', 'fish', 'fluent', 'fortran-fixed-form', 'fortran-free-form', 'fsharp', 'gdresource', 'gdscript', 'gdshader', 'genie', 'gherkin', 'git-commit', 'git-rebase', 'gleam', 'glimmer-js', 'glimmer-ts', 'glsl', 'gnuplot', 'go', 'graphql', 'groovy', 'hack', 'haml', 'handlebars', 'haskell', 'haxe', 'hcl', 'hjson', 'hlsl', 'html', 'html-derivative', 'http', 'hxml', 'hy', 'imba', 'ini', 'java', 'javascript', 'jinja', 'jison', 'json', 'json5', 'jsonc', 'jsonl', 'jsonnet', 'jssm', 'jsx', 'julia', 'kotlin', 'kusto', 'latex', 'lean', 'less', 'liquid', 'log', 'logo', 'lua', 'luau', 'make', 'markdown', 'marko', 'matlab', 'mdc', 'mdx', 'mermaid', 'mipsasm', 'mojo', 'move', 'narrat', 'nextflow', 'nginx', 'nim', 'nix', 'nushell', 'objective-c', 'objective-cpp', 'ocaml', 'pascal', 'perl', 'php', 'plsql', 'po', 'postcss', 'powerquery', 'powershell', 'prisma', 'prolog', 'proto', 'pug', 'puppet', 'purescript', 'python', 'qml', 'qmldir', 'qss', 'r', 'racket', 'raku', 'razor', 'reg', 'regexp', 'rel', 'riscv', 'rst', 'ruby', 'rust', 'sas', 'sass', 'scala', 'scheme', 'scss', 'sdbl', 'shaderlab', 'shellscript', 'shellsession', 'smalltalk', 'solidity', 'soy', 'sparql', 'splunk', 'sql', 'ssh-config', 'stata', 'stylus', 'svelte', 'swift', 'system-verilog', 'systemd', 'talonscript', 'tasl', 'tcl', 'templ', 'terraform', 'tex', 'toml', 'ts-tags', 'tsv', 'tsx', 'turtle', 'twig', 'typescript', 'typespec', 'typst', 'v', 'vala', 'vb', 'verilog', 'vhdl', 'viml', 'vue', 'vue-html', 'vyper', 'wasm', 'wenyan', 'wgsl', 'wikitext', 'wolfram', 'xml', 'xsl', 'yaml', 'zenscript', 'zig', 'adoc', 'batch', 'be', '1c', 'cdc', 'clj', 'ql', 'coffeescript', 'lisp', 'c++', 'c#', 'cs', 'cql', 'dockerfile', 'elisp', 'erl', 'ftl', 'f', 'for', 'f77', 'f90', 'f95', 'f03', 'f08', 'f18', 'f#', 'fs', 'gjs', 'gts', 'gql', 'hbs', 'hs', 'properties', 'js', 'fsl', 'jl', 'kt', 'kts', 'kql', 'lean4', 'makefile', 'md', 'mmd', 'mips', 'nar', 'nf', 'nu', 'objc', 'pot', 'potx', 'ps', 'ps1', 'protobuf', 'jade', 'py', 'perl6', 'regex', 'rb', 'rs', '1c-query', 'shader', 'bash', 'sh', 'shell', 'zsh', 'console', 'closure-templates', 'spl', 'styl', 'talon', 'tf', 'tfvars', 'lit', 'ts', 'tsp', 'typ');
    CREATE TYPE "public"."enum_experience_posts_blocks_script_copy_btn_code_language" AS ENUM('abap', 'actionscript-3', 'ada', 'angular-html', 'angular-ts', 'apache', 'apex', 'apl', 'applescript', 'ara', 'asciidoc', 'asm', 'astro', 'awk', 'ballerina', 'bat', 'beancount', 'berry', 'bibtex', 'bicep', 'blade', 'bsl', 'c', 'cadence', 'cairo', 'clarity', 'clojure', 'cmake', 'cobol', 'codeowners', 'codeql', 'coffee', 'common-lisp', 'coq', 'cpp', 'crystal', 'csharp', 'css', 'csv', 'cue', 'cypher', 'd', 'dart', 'dax', 'desktop', 'diff', 'docker', 'dotenv', 'dream-maker', 'edge', 'elixir', 'elm', 'emacs-lisp', 'erb', 'erlang', 'fennel', 'fish', 'fluent', 'fortran-fixed-form', 'fortran-free-form', 'fsharp', 'gdresource', 'gdscript', 'gdshader', 'genie', 'gherkin', 'git-commit', 'git-rebase', 'gleam', 'glimmer-js', 'glimmer-ts', 'glsl', 'gnuplot', 'go', 'graphql', 'groovy', 'hack', 'haml', 'handlebars', 'haskell', 'haxe', 'hcl', 'hjson', 'hlsl', 'html', 'html-derivative', 'http', 'hxml', 'hy', 'imba', 'ini', 'java', 'javascript', 'jinja', 'jison', 'json', 'json5', 'jsonc', 'jsonl', 'jsonnet', 'jssm', 'jsx', 'julia', 'kotlin', 'kusto', 'latex', 'lean', 'less', 'liquid', 'log', 'logo', 'lua', 'luau', 'make', 'markdown', 'marko', 'matlab', 'mdc', 'mdx', 'mermaid', 'mipsasm', 'mojo', 'move', 'narrat', 'nextflow', 'nginx', 'nim', 'nix', 'nushell', 'objective-c', 'objective-cpp', 'ocaml', 'pascal', 'perl', 'php', 'plsql', 'po', 'postcss', 'powerquery', 'powershell', 'prisma', 'prolog', 'proto', 'pug', 'puppet', 'purescript', 'python', 'qml', 'qmldir', 'qss', 'r', 'racket', 'raku', 'razor', 'reg', 'regexp', 'rel', 'riscv', 'rst', 'ruby', 'rust', 'sas', 'sass', 'scala', 'scheme', 'scss', 'sdbl', 'shaderlab', 'shellscript', 'shellsession', 'smalltalk', 'solidity', 'soy', 'sparql', 'splunk', 'sql', 'ssh-config', 'stata', 'stylus', 'svelte', 'swift', 'system-verilog', 'systemd', 'talonscript', 'tasl', 'tcl', 'templ', 'terraform', 'tex', 'toml', 'ts-tags', 'tsv', 'tsx', 'turtle', 'twig', 'typescript', 'typespec', 'typst', 'v', 'vala', 'vb', 'verilog', 'vhdl', 'viml', 'vue', 'vue-html', 'vyper', 'wasm', 'wenyan', 'wgsl', 'wikitext', 'wolfram', 'xml', 'xsl', 'yaml', 'zenscript', 'zig', 'adoc', 'batch', 'be', '1c', 'cdc', 'clj', 'ql', 'coffeescript', 'lisp', 'c++', 'c#', 'cs', 'cql', 'dockerfile', 'elisp', 'erl', 'ftl', 'f', 'for', 'f77', 'f90', 'f95', 'f03', 'f08', 'f18', 'f#', 'fs', 'gjs', 'gts', 'gql', 'hbs', 'hs', 'properties', 'js', 'fsl', 'jl', 'kt', 'kts', 'kql', 'lean4', 'makefile', 'md', 'mmd', 'mips', 'nar', 'nf', 'nu', 'objc', 'pot', 'potx', 'ps', 'ps1', 'protobuf', 'jade', 'py', 'perl6', 'regex', 'rb', 'rs', '1c-query', 'shader', 'bash', 'sh', 'shell', 'zsh', 'console', 'closure-templates', 'spl', 'styl', 'talon', 'tf', 'tfvars', 'lit', 'ts', 'tsp', 'typ');
    CREATE TYPE "public"."enum__experience_posts_v_blocks_script_copy_btn_code_language" AS ENUM('abap', 'actionscript-3', 'ada', 'angular-html', 'angular-ts', 'apache', 'apex', 'apl', 'applescript', 'ara', 'asciidoc', 'asm', 'astro', 'awk', 'ballerina', 'bat', 'beancount', 'berry', 'bibtex', 'bicep', 'blade', 'bsl', 'c', 'cadence', 'cairo', 'clarity', 'clojure', 'cmake', 'cobol', 'codeowners', 'codeql', 'coffee', 'common-lisp', 'coq', 'cpp', 'crystal', 'csharp', 'css', 'csv', 'cue', 'cypher', 'd', 'dart', 'dax', 'desktop', 'diff', 'docker', 'dotenv', 'dream-maker', 'edge', 'elixir', 'elm', 'emacs-lisp', 'erb', 'erlang', 'fennel', 'fish', 'fluent', 'fortran-fixed-form', 'fortran-free-form', 'fsharp', 'gdresource', 'gdscript', 'gdshader', 'genie', 'gherkin', 'git-commit', 'git-rebase', 'gleam', 'glimmer-js', 'glimmer-ts', 'glsl', 'gnuplot', 'go', 'graphql', 'groovy', 'hack', 'haml', 'handlebars', 'haskell', 'haxe', 'hcl', 'hjson', 'hlsl', 'html', 'html-derivative', 'http', 'hxml', 'hy', 'imba', 'ini', 'java', 'javascript', 'jinja', 'jison', 'json', 'json5', 'jsonc', 'jsonl', 'jsonnet', 'jssm', 'jsx', 'julia', 'kotlin', 'kusto', 'latex', 'lean', 'less', 'liquid', 'log', 'logo', 'lua', 'luau', 'make', 'markdown', 'marko', 'matlab', 'mdc', 'mdx', 'mermaid', 'mipsasm', 'mojo', 'move', 'narrat', 'nextflow', 'nginx', 'nim', 'nix', 'nushell', 'objective-c', 'objective-cpp', 'ocaml', 'pascal', 'perl', 'php', 'plsql', 'po', 'postcss', 'powerquery', 'powershell', 'prisma', 'prolog', 'proto', 'pug', 'puppet', 'purescript', 'python', 'qml', 'qmldir', 'qss', 'r', 'racket', 'raku', 'razor', 'reg', 'regexp', 'rel', 'riscv', 'rst', 'ruby', 'rust', 'sas', 'sass', 'scala', 'scheme', 'scss', 'sdbl', 'shaderlab', 'shellscript', 'shellsession', 'smalltalk', 'solidity', 'soy', 'sparql', 'splunk', 'sql', 'ssh-config', 'stata', 'stylus', 'svelte', 'swift', 'system-verilog', 'systemd', 'talonscript', 'tasl', 'tcl', 'templ', 'terraform', 'tex', 'toml', 'ts-tags', 'tsv', 'tsx', 'turtle', 'twig', 'typescript', 'typespec', 'typst', 'v', 'vala', 'vb', 'verilog', 'vhdl', 'viml', 'vue', 'vue-html', 'vyper', 'wasm', 'wenyan', 'wgsl', 'wikitext', 'wolfram', 'xml', 'xsl', 'yaml', 'zenscript', 'zig', 'adoc', 'batch', 'be', '1c', 'cdc', 'clj', 'ql', 'coffeescript', 'lisp', 'c++', 'c#', 'cs', 'cql', 'dockerfile', 'elisp', 'erl', 'ftl', 'f', 'for', 'f77', 'f90', 'f95', 'f03', 'f08', 'f18', 'f#', 'fs', 'gjs', 'gts', 'gql', 'hbs', 'hs', 'properties', 'js', 'fsl', 'jl', 'kt', 'kts', 'kql', 'lean4', 'makefile', 'md', 'mmd', 'mips', 'nar', 'nf', 'nu', 'objc', 'pot', 'potx', 'ps', 'ps1', 'protobuf', 'jade', 'py', 'perl6', 'regex', 'rb', 'rs', '1c-query', 'shader', 'bash', 'sh', 'shell', 'zsh', 'console', 'closure-templates', 'spl', 'styl', 'talon', 'tf', 'tfvars', 'lit', 'ts', 'tsp', 'typ');

    -- Step 4: Reapply the enum types to the columns
    ALTER TABLE "public"."pages_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum_pages_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum_pages_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."blog_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum_blog_posts_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum_blog_posts_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."_blog_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum__blog_posts_v_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum__blog_posts_v_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."experience_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum_experience_posts_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum_experience_posts_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."_experience_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum__experience_posts_v_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum__experience_posts_v_blocks_script_copy_btn_code_language";
  `);
}

export async function down({
  db,
  payload,
  req,
}: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    -- Step 1: Temporarily change the column type to text
    ALTER TABLE "public"."pages_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."blog_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."_blog_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."experience_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;
    ALTER TABLE "public"."_experience_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE text;

    -- Step 2: Drop the new enum types
    DROP TYPE "public"."enum_pages_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum_blog_posts_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum__blog_posts_v_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum_experience_posts_blocks_script_copy_btn_code_language";
    DROP TYPE "public"."enum__experience_posts_v_blocks_script_copy_btn_code_language";

    -- Step 3: Recreate old enum types
    CREATE TYPE "public"."enum_pages_blocks_script_copy_btn_code_language" AS ENUM('shell', 'typescript', 'javascript', 'python');
    CREATE TYPE "public"."enum_blog_posts_blocks_script_copy_btn_code_language" AS ENUM('shell', 'typescript', 'javascript', 'python');
    CREATE TYPE "public"."enum__blog_posts_v_blocks_script_copy_btn_code_language" AS ENUM('shell', 'typescript', 'javascript', 'python');
    CREATE TYPE "public"."enum_experience_posts_blocks_script_copy_btn_code_language" AS ENUM('shell', 'typescript', 'javascript', 'python');
    CREATE TYPE "public"."enum__experience_posts_v_blocks_script_copy_btn_code_language" AS ENUM('shell', 'typescript', 'javascript', 'python');

    -- Step 4: Reapply the old enum types to the columns
    ALTER TABLE "public"."pages_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum_pages_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum_pages_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."blog_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum_blog_posts_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum_blog_posts_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."_blog_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum__blog_posts_v_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum__blog_posts_v_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."experience_posts_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum_experience_posts_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum_experience_posts_blocks_script_copy_btn_code_language";
    ALTER TABLE "public"."_experience_posts_v_blocks_script_copy_btn" ALTER COLUMN "code_language" SET DATA TYPE "public"."enum__experience_posts_v_blocks_script_copy_btn_code_language" USING "code_language"::"public"."enum__experience_posts_v_blocks_script_copy_btn_code_language";
  `);
}
